server:
   port: 8083  #端口号
   
spring:
   datasource:
      #url: jdbc:sqlserver://172.16.201.160:1433;DatabaseName=hemodialysis_XY
      url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=wfy
      username: sa
      #password: Huamai521
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: -1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      cachePrepStmts: true  # 开启二级缓存
   thymeleaf:
      mode: HTML5
      encoding: UTF-8
      cache: false #开发时关闭缓存,不然没法看到实时页面   热部署静态文件
mybatis:
   typeAliasesPackage: com.huamai.hdServer.mapper
   mapperLocations: classpath:com/huamai/hdServer/mapper/*.xml
   mapperScanPackage: com.huamai.hdServer.mapper
   configLocation: classpath:/mybatis-config.xml
   
pagehelper:
    helperDialect: sqlserver
    
# 打印sql
logging:
  level:
     com.huamai.hdServer.mapper : debug  #包路径为mapper文件包路径
     
   
   
